Running "main" (2 tests)...
first_tests.c:12: Failure: fails_this_test 
	Expected [0 == 1] to [be true]

Completed "main": 1 pass, 1 failure in 27ms.
