Running "person_tests" (2 tests)...
schema_tests.c:29: Failure: can_add_person_to_database 
	Expected [get_person_name(found)] to [equal string] ["Fred"]
		actual value:			["(null)"]
		expected to equal:		["Fred"]

schema_tests.c:38: Failure: cannot_add_duplicate_person 
	Expected [save_person(duplicate)] to [be false]

Completed "person_tests": 1 pass, 2 failures in 40ms.
